name: app_gokai
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.5.0-177.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter






  cupertino_icons: ^1.0.8 #Ios Icon #use
  dio: ^5.4.3+1 # http package internet data #use
  shared_preferences: ^2.2.3 #simple data store local #use
  flutter_riverpod: ^2.5.1 # state management package
  cached_network_image: ^3.3.1 # image save ofline #use
  feedback: ^3.1.0 # user feedback and issue send
  google_fonts: ^6.2.1 # text fonts change
  day_night_switcher: ^0.2.0+1 # dark and light mode
  search_page: ^2.3.0 # search data in list #use
  flutter_staggered_grid_view: ^0.7.0 # different size list show 
  url_launcher: ^6.3.0 # click to navigate #use
  connectivity_plus: ^5.0.0 # internet check #use
  webview_flutter: ^2.0.0 # website show #use
  device_preview: ^1.1.0 # remove production time 
  gap: ^3.0.1 # ui helper
  flutter_platform_widgets: ^7.0.0 # the package use ios style show 
  flutter_emoji_feedback: ^0.3.0 # when user exit apps then show
  lottie: ^3.1.2 # lottie animation show #use
  auto_size_text: ^3.0.0 # when many text then text size is smail #use
  # dotted_border: ^2.1.0 # dot border make time
  flutter_staggered_animations: ^1.1.1 # list animation
  flutter_animate: ^4.5.0 # optional animation
  animated_text_kit: ^4.2.2 # text animation
  badges: ^3.1.2 # notification badges
  page_transition: ^2.1.0 # animated page navigation #use
  in_app_review: ^2.0.9 # app review
  modal_bottom_sheet: ^3.0.0 # ui package
  upgrader: ^10.3.0 # when new version app dialog show plz update app
  # google_mobile_ads: ^2.4.0 # google ads show
  firebase_core: ^3.1.0 # firebase app connect
  firebase_remote_config: ^5.0.1 # apps ui change without update
  cloud_firestore: ^5.0.1 # extra website add user send
  in_app_purchase: ^3.2.0 # don't show ads plz buy apps
  flutter_donation_buttons: ^0.4.10 # or donation remove ads
  awesome_notifications: ^0.9.3+1 # apps notication send
  flutter_app_badger: ^1.5.0 # notication when send without seen when badget show
  tuple: ^2.0.2 # error handling
  icons_launcher: ^2.1.7 # flutter app icon #use
  http: ^1.2.1 # http package internet data #use
  flutter_email_sender: ^5.1.0 #feedback email send #use
  path_provider: ^2.1.3 #feedback email image sceenshot send #use
  floating_bottom_navigation_bar: ^1.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

icons_launcher:
  image_path: "assets/image/appicon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter:

  uses-material-design: true
  assets:
    - assets/image/appicon.png
    - assets/lottie/nointernet.json



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700