name: app_gokai
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.5.0-177.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  dio: ^5.4.3+1
  shared_preferences: ^2.2.3
  flutter_riverpod: ^2.5.1
  cached_network_image: ^3.3.1
  feedback: ^3.1.0
  google_fonts: ^6.2.1
  day_night_switcher: ^0.2.0+1
  search_page: ^2.3.0
  flutter_staggered_grid_view: ^0.7.0
  url_launcher: ^6.3.0
  connectivity_plus: ^6.0.3
  webview_flutter: ^2.0.0
  device_preview: ^1.1.0
  icons_launcher: ^2.1.7
  flutter_platform_widgets: ^7.0.0
  flutter_emoji_feedback: ^0.3.0
  flutter_staggered_animations: ^1.1.1
  carousel_slider: ^4.2.1
  lottie: ^3.1.2
  auto_size_text: ^3.0.0
  dotted_border: ^2.1.0
  flutter_animate: ^4.5.0
  badges: ^3.1.2
  page_transition: ^2.1.0
  in_app_review: ^2.0.9
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700